export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"

export const SET_USER_BY_TOKEN = "SET_USER_BY_TOKEN"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_UPDATED = "USER_UPDATED"

export const APOLLO_QUERY_RESULT = "APOLLO_QUERY_RESULT"
export const APOLLO_MUTATION_RESULT = "APOLLO_MUTATION_RESULT"
export const APOLLO_QUERY_RESULT_CLIENT = "APOLLO_QUERY_RESULT_CLIENT"
export const APOLLO_MUTATION_RESULT_CLIENT = "APOLLO_MUTATION_RESULT_CLIENT"

export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE"
